import type { CampaignDefinition } from "./types.js";

export const lengendNightmareCampaign: CampaignDefinition = {
  id: "lengend-nightmare",
  version: 1,
  player: {
    id: "stitched-champion",
    name: "The Creature",
    maxHp: 100,
    maxEnergy: 3,
  },
  actions: [
    {
      id: "attack",
      label: "Clobber",
      cost: 0,
      detail: "Deal 13–19 damage",
      effect: "damage",
      minValue: 13,
      maxValue: 19,
    },
    {
      id: "stitch",
      label: "Stitch Up",
      cost: 2,
      detail: "Restore 18–25 vitality",
      effect: "heal",
      minValue: 18,
      maxValue: 25,
    },
    {
      id: "overcharge",
      label: "Overcharge",
      cost: 3,
      detail: "Deal 28–38 damage",
      effect: "damage",
      minValue: 28,
      maxValue: 38,
    },
    {
      id: "guard",
      label: "Brace",
      cost: 1,
      detail: "Reduce the next hit",
      effect: "guard",
      minValue: 0,
      maxValue: 0,
    },
  ],
  levels: [
    ["The Awakening", "CHAPTER I · SPARKS", "The Lightning Lab", "Wake the stitched champion.", "The Dusty Attendant", "Slow to anger", "slow", 42, 5, 9, "Copper Heart"],
    ["Turf and Turf", "CHAPTER II · TERRITORY", "The Moss Courtyard", "Claim the courtyard gates.", "Mossback Rook", "Braced", "braced", 54, 6, 10, "Reinforced Bolts"],
    ["A Very Tall Order", "CHAPTER III · ELEVATION", "The Bell Tower", "Ring the bell before sunrise.", "The Bell Golem", "Heavy hitter", "heavy", 66, 8, 13, "Longer Fuse"],
    ["Dinner Is Served", "CHAPTER IV · FEAST", "The Banquet Crypt", "Survive the table manners.", "Countess Calamari", "Regenerates", "regenerates", 71, 6, 11, "Velvet Bandages"],
    ["The Unkindest Cut", "CHAPTER V · RIVALRY", "The Mirror Hall", "Outwit your reflected self.", "The Spare Parts", "Mimic", "mimic", 78, 8, 14, "Chrome Knuckles"],
    ["A Horse of Course", "CHAPTER VI · CHASE", "The Rattle Road", "Cross the haunted causeway.", "Nightmare Knight", "Charges hard", "charger", 84, 9, 15, "Tendon Springs"],
    ["Bog Standard", "CHAPTER VII · DEPTHS", "The Green Mire", "Find the lantern beneath the sludge.", "Bog Witch", "Drains energy", "drainer", 91, 7, 13, "Mireproof Skin"],
    ["The Last Laugh", "CHAPTER VIII · COMEDY", "The Punishment Stage", "Make the audience blink.", "The Laughing Jack", "Unpredictable", "chaotic", 96, 6, 16, "Jester's Spark"],
    ["Castle Call", "CHAPTER IX · ASCENT", "Castle Thunder", "Climb to the tournament roof.", "The Crowned Bride", "Royal guard", "royal-guard", 112, 10, 16, "A Brass Crown"],
    ["The Big Stitch", "CHAPTER X · FINALE", "The Tournament Board", "Defeat the maker of monsters.", "Dr. Victor Vile", "Final boss", "final-boss", 140, 11, 18, "Legend of the Night"],
  ].map(([title, chapter, environment, objective, enemy, trait, behavior, hp, attackMin, attackMax, reward], index) => ({
    id: index + 1,
    title: title as string,
    chapter: chapter as string,
    environment: environment as string,
    objective: objective as string,
    enemy: {
      id: String(enemy).toLowerCase().replace(/[^a-z0-9]+/g, "-"),
      name: enemy as string,
      hp: hp as number,
      trait: trait as string,
      behavior: behavior as "slow",
      attackMin: attackMin as number,
      attackMax: attackMax as number,
    },
    reward: reward as string,
  })),
};